### PR TITLE
Prevent blank context, test added.

### PR DESCRIPTION
**Pull request by brl0**
Addresses #99. Shell starts with empty context when konch is launched via `python konch.py` or `python -m konch`.
New test for issue added.
It was a challenge to write this in a way that passed mypy, which is why the new get_config function may seem convoluted, although it is possible I am just missing a simpler solution.

### CODE REVIEW

**Comment by brl0** [comment]
Addresses #99.  Shell starts with empty context when konch is launched via `python konch.py` or `python -m konch`.  
New test for issue added.
It was a challenge to write this in a way that passed mypy, which is why the new get_config function may seem convoluted, although it is possible I am just missing a simpler solution.

**Comment by brl0** [comment]
I don't know why the CI checks are failing, tox and pytest ran without issues in a docker environment locally.  Perhaps I have been looking at this for too long, but I am a bit stumped by this.  Any suggestions about how to troubleshoot this?  

On the upside, everything seems to be working properly on my system, so I think I am getting close.  Although to be honest, I don't think my solution is as pretty, concise, or idiomatic as I would like.  I would be eager for any specific feedback to help me improve the quality of what I have written.

**Comment by sloria** [comment]
Again, this contains unrelated changes. Please separate your fixes into separate branches/PRs.

**Comment by brl0** [comment]
While this PR still requires additional work to pass all test in CI, the solutions to the two problems have become integrated in such a way that would be difficult to separate.  I don't think these changes are unrelated.  I will try to rethink it and see if I can come up with something.
Thanks for your time and assistance.

**Pull request closed without merging**
