### PR TITLE
Update to use importlib.

### PR DESCRIPTION
**Pull request by brl0**

### CODE REVIEW

**Comment by sloria** [comment]
Is there a reason you didn't use this approach from the docs: https://docs.python.org/3.7/library/importlib.html#importing-a-source-file-directly ?

**Comment by brl0** [comment]
I didn't look too much further after finding a solution that worked.  I thought that the approach I used was a bit closer to a drop in replacement and would therefore require the least overall code changes.  But again, I did not spend a lot of time once I found a workable solution, so there may very well be better solutions available.

**Comment by brl0** [comment]
The recipe in the linked docs assumes a `.py` extension, which is why it doesn't work as-is.  Found this [answer](https://stackoverflow.com/a/43602557/10293068), which is needed to make the recipe work correctly in this particular case.  Also had to add an `assert` to make MyPy happy.

**Comment by sloria** [comment]
The solution was actually simpler. See https://github.com/sloria/konch/pull/109 . Thanks for your initial work on this.

**Pull request closed without merging**
