### PR TITLE
Ensure _cfg loaded, rename to _konch_cfg

### PR DESCRIPTION
**Pull request by brl0**
Rename `_cfg` to `_konch_cfg`.  Search loaded `.konchrc` module for `_konch_cfg` and update global if found.  Added test for issue.

### CODE REVIEW

**Comment by brl0** [comment]
I realize this PR is probably a pain to review.  Let me know if you want me to break it up.  My goal here is to help with a project I enjoy, not create extra work or pain points for its maintainer.  :)

**Comment by sloria** [comment]
The approach here still feels more complex and bug-prone than I'm comfortable adding to the codebase.

I think if you want to run konch with the `python` command, your best bet is to add a script to your project that runs `konch.main()`. Something like

```python
# myproject/shell.py
import konch

konch.main()
```

You can then do

```
python3 shell.py
```

Does that meet your use case?

By the way, I really appreciate you helping out! Even though your PRs may not get merged, your research into these issues is a big help.

**Comment by brl0** [comment]
> The approach here still feels more complex and bug-prone than I'm comfortable adding to the codebase.

I honestly completely understand your concern.  Although I also would like to point out that I tried to mitigate the intrusiveness of this solution by only doing additional stuff if the `_cfg` is not already properly loaded.  So for most existing use case, the code flow will be minimally impacted.  Only when the `_cfg` was not properly loaded the script will search the `.konchrc` module for a `_konch_cfg` object.

I also appreciate that your responsibility is keeping the project as stable as possible, so understand If my changes don't make it.  If anything, it does make me wonder what I should have done better through this process.

Thanks for you attention, time, and patience on this issue.  It has really been a growing opportunity for me.

**Comment by sloria** [comment]
My only suggestion is to try to keep PRs as small and focused as possible, e.g. keep fixes separate from refactors/renames. That's not a blocker here, though.

Otherwise, the code here isn't so much a problem. Indeed, the code you added is pretty localized. It's more an issue of risk; if a bug arises, the code will be tough to debug. The risk isn't worth taking when there's already a way to meet the OP (by using konch programmatically as suggested above).

Again, thanks for your work on konch thus far.

**Pull request closed without merging**
